apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "network-enforcer.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "network-enforcer.caIssuerName" . }}
  labels:
  {{- include "network-enforcer.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "network-enforcer.fullname" . }}-controller-webhook
      namespace: {{ .Release.Namespace }}
      path: /validate-security-rancher-io-v1alpha1-workloadnetworkpolicyproposal
  failurePolicy: Fail
  name: validate-workloadnetworkpolicyproposals.rancher.io
  matchConditions:
  - name: promote-label-present
    expression: 'has(object.metadata.labels) && "security.rancher.io/promote" in object.metadata.labels'
  rules:
  - apiGroups:
    - security.rancher.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workloadnetworkpolicyproposals
  sideEffects: None
